navbar:
  title: iwanttrails.com
home: # Home section with background images.
  href: home
  text: <h1 class="display-1 fw-bold">HIKE. BIKE. RIDE.</h1>
        <h2 class="display-5 fw-bold">On your land.</h2>
  image: static/img/home.jpg
  image_mobile: static/img/home.jpg
sections: # List of sections along with background images.
- name: Services # Name of section displayed in a list box that scrolls over bg image.
  href: services # Must match NAVBAR href.
  justify_topics: start # Position of list box.
  image: static/img/services.jpg # Desktop bg image.
  image_mobile: static/img/services.jpg # Mobile bg image.
  # Each section has a list of topics with associated directories.
  # Within each directory can be multiple images and associated captions.
  # e.g., image1.jpg and image1.txt, alpha-numeric ordered.
  topics:
  - name: Trail Construction
    path: static/img/services/construction
  - name: Trail Consulting
    path: static/img/services/consulting
  - name: Trail Repairs
    path: static/img/services/repairs
  - name: Small Projects
    path: static/img/services/projects
  - name: Areas Served
    path: static/img/abouts/areas
- name: About Me
  href: abouts
  justify_topics: end
  image: static/img/abouts.jpg
  image_mobile: static/img/abouts.jpg
  topics:
  - name: Background
    path: static/img/abouts/background
  - name: Experience
    path: static/img/abouts/experience
  - name: Tools
    path: static/img/abouts/tools
  - name: Areas Served
    path: static/img/abouts/areas
- name: Gallery
  href: gallery
  justify_topics: center
  image: static/img/gallery.jpg
  image_mobile: static/img/gallery.jpg
  paths: [static/img/gallery,]
  images: []
contact: # Contact section, may require updating index.html and app.py for your application.
  justify_topics: end
  image: static/img/contact.jpg
  image_mobile: static/img/contact.jpg
